# A reveiw of some of the research I have conducted in sprint 0.

## Similar projects
These are papers which document previous attempts at using open source
data in order to forcast football results.

[Modeling and Prediction of the UEFA EURO 2024
via Combined Statistical Learning Approaches](https://arxiv.org/pdf/2410.09068)
* A. Groll et al, 2024
* Prediction of the 2024 euros, could provide a framework through which we look to simulate results
* This is for international football which means some features such as GDP are not applicable to our analysis.
* They are using poisson model for expected goals and hence result, maybe this is a limitation and something like dixon coles would be more appropriate?
* Uses all the classic ML methods ie LASSO, random forests, ext. grad boosting .
* Their use of ext grad boosting was limited due to small data available for parameter tuning

[Hybrid Machine Learning Forecasts for the UEFA
EURO 2020](https://arxiv.org/pdf/2106.05799)
* A. Groll et al, 2021
* Has greater discussion on the data gathered and use of engineered features.

[The Evolution of Football Betting: A Machine Learning Approach to Match Outcome
Forecasting and Bookmaker Odds Estimation](https://arxiv.org/pdf/2403.16282)
* P. Mandadapu
* Honestly seems like a pretty shallow paper, maybe similar to type of work we should aim to improve upon?
* Necessitates webscraping for fbref data, which would be slightly annoying but i think more than do able.
* Could use similar framework but intorduce the more accurate odds from framework for football prediction, as well as further feature engineering ie including team strength data rather than whatever they did. Create a rating feature etc...


## Found datasets
A few collated datasets from which we can begin our analysis

[Events: from 2011/2012 season to 2016/2017 season](https://www.kaggle.com/datasets/secareanualin/football-events/data)  
*   Contains 9,074 games, totaling 941,009 events
*   Big 5 leagues
*   From scraped text commentaries
*   Would be good for emulating the cricket prediction with time series work

[player datasets](https://www.kaggle.com/datasets/rishikeshkanabar/premier-league-player-statistics-updated-daily)
* Players in prem teams 2020 season
* Pretty small
* Maybe useful for feature engineering

[FM23 player database](https://www.kaggle.com/datasets/siddhrajthakor/football-manager-2023-dataset)
* The football manager 23 player database
* Big data, would be useful for team ratings maybe
* Maybe usful for feature engineering

## Other Resources
Found resources which may be of use throughout the project. 
The tutorials could be useful as an introduction to the ML methods.


[Extensive lecture notes on R](https://www.modernstatisticswithr.com/regression.html)
* Provides pretty all encompassing overview of R, r code, and some modern statistical methods. Seems pretty sick

[When should key performance indicators be considered absolutely vs relativley](https://arxiv.org/pdf/2504.19612)
* Could be used as a theoretical framework / additional feature so as to determine how to represent key performance indicators, icl idrk what it means.

[Random forest tutorial](https://www.kaggle.com/code/prashant111/random-forest-classifier-tutorial)
* A tutorial covering the basics of random forests

[XGB tutorial](https://www.kaggle.com/code/alirezahasannejad/xgboost-classifier-tutorial)
* Acutually not sure how helpful this one will be

[LASSO tutorial](https://machinelearningmastery.com/lasso-regression-with-python/)