---
title: "ML S0 doc"
author: "Mathilde Launay"
date: "2026-10-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Data that I found comes from https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017?resource=download
Then I just copied and pasted what was on the website to give more context (Look at the bottom of the page for comments on data suitability):

#Content

This dataset includes 49,393 results of international football matches starting from the very first official match in 1872 up to 2025. The matches range from FIFA World Cup to FIFI Wild Cup to regular friendly matches. The matches are strictly men's full internationals and the data does not include Olympic Games or matches where at least one of the teams was the nation's B-team, U-23 or a league select team.


results.csv includes the following columns:

date - date of the match
home_team - the name of the home team
away_team - the name of the away team
home_score - full-time home team score including extra time, not including penalty-shootouts
away_score - full-time away team score including extra time, not including penalty-shootouts
tournament - the name of the tournament
city - the name of the city/town/administrative unit where the match was played
country - the name of the country where the match was played
neutral - TRUE/FALSE column indicating whether the match was played at a neutral venue


shootouts.csv includes the following columns:

date - date of the match
home_team - the name of the home team
away_team - the name of the away team
winner - winner of the penalty-shootout
first_shooter - the team that went first in the shootout


goalscorers.csv includes the following columns:

date - date of the match
home_team - the name of the home team
away_team - the name of the away team
team - name of the team scoring the goal
scorer - name of the player scoring the goal
own_goal - whether the goal was an own-goal
penalty - whether the goal was a penalty


former_names.csv includes the following columns:

current - name of the team as is used currently (or the last name if the team does not exist anymore)
former - former name used by said team
start_date - start date of when former name was used
end_date - end date of when former name was used


#Dataset suitability:

The advantage of this dataset is the amount of data that is recorded. The issue is that it is messy and there are a lot of different sections, so it would need a bit of processing to be usable.
For example, there are different country names that need to be combined into one. Also, there are a lot of different types of tournaments, with too many different teams, so it would be a lot of effort to get details about every single team and player. 
Given that we are looking for a variety of covariates, it would be very computationally expensive if all of these categorical covariates consisted of many different sections. 
It would also be hard to make predictions, unless we chose a subset of the data for modeling, but in which case we would be working with a much smaller dataset.
In conclusion, due to the fact that a lot of data pre-processing is needed and that after this pre-processing happens, we may be left with a significantly smaller dataset, this dataset is not suitable for this group project. 

These conclusions were made from generating pivot tables that can be found on sheet 2 and sheet 3 in the Excel data file.